INSERT INTO DEPT_LOCATIONS
VALUES (1, 'Houston');

INSERT INTO DEPT_LOCATIONS
VALUES (4, 'Stafford');

INSERT INTO DEPT_LOCATIONS
VALUES (5, 'Bellair');

INSERT INTO DEPT_LOCATIONS
VALUES (5, 'Sugarland');

INSERT INTO DEPT_LOCATIONS
VALUES (5, 'Houston');