<?php

use \general\WebApp;
?>
<div class="employees row gutters-sm my-3">
    <form class="container border col-md-4" method="post" action="<?php echo WebApp::getUrlPath("/employee"); ?>">
        <h3 class="my-3 text-center">Add an Employee</h3>
        <div class="mb-3">
            <label class="col-form-label fw-bold" for="Ssn">Employee Social Security Number is:</label>
            <input type="text" class="form-control <?= !$errors['Ssn'] ?: 'is-invalid'; ?>" name="Ssn" required>
            <div class="invalid-feedback">
                <?= $errors['Ssn'][0]; ?>
            </div>
        </div>
        <div class="mb-3">
            <label class="col-form-label fw-bold" for="Lname">Employee Last name is:</label>
            <input type="text" class="form-control <?= !$errors['Lname'] ?: 'is-invalid'; ?>" name="Lname" required>
            <div class="invalid-feedback">
                <?= $errors['Lname'][0]; ?>
            </div>
        </div>
        <div class="my-3">
            <label class="col-form-label fw-bold" for="Fname">Employee First name is:</label>
            <input type="text" class="form-control <?= !$errors['Fname'] ?: 'is-invalid'; ?>" name="Fname" required>
            <div class="invalid-feedback">
                <?= $errors['Fname'][0]; ?>
            </div>
        </div>
        <div class="my-3">
            <label class="col-form-label fw-bold" for="Address">Employee Address is:</label>
            <input type="text" class="form-control" name="Address">
        </div>
        <div class="my-3">
            <label class="col-form-label fw-bold" for="Salary">Employee Salary is:</label>
            <input type="text" class="form-control" name="Salary">
        </div>
        <div class="my-3">
            <label class="col-form-label fw-bold" for="Dno">Department Number is:</label>
            <input type="text" class="form-control <?= !$errors['Dno'] ?: 'is-invalid'; ?>" name="Dno" required>
            <div class="invalid-feedback">
                <?= $errors['Dno'][0]; ?>
            </div>
        </div>
        <button type="submit" class="btn btn-primary my-3" name="submit">Add</button>
    </form>
    <div class="col-md-8">
        <table class="table">
            <thead class="thead-primary">
                <tr>
                    <th scope="col">SSN</th>
                    <th scope="col">Name</th>
                    <th scope="col">Address</th>
                    <th scope="col">Salary</th>
                    <th scope="col">Options</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($employees as $employee) { ?>
                    <tr>
                        <th scope="row"><a href="<?php echo WebApp::getUrlPath("/employee?ssn=" . $employee->getData('Ssn')); ?>"><?= $employee->getData('Ssn'); ?></a></th>
                        <td><?= $employee->Fname . " " . $employee->Lname; ?></td>
                        <td><?= $employee->Address; ?></td>
                        <td><?= $employee->Salary; ?></td>
                        <td><?= "Add" ?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>