<table class="table">
    <thead class="thead-primary">
        <tr>
            <th scope="col">SSN</th>
            <th scope="col">Name</th>
            <th scope="col">Address</th>
            <th scope="col">Salary</th>
            <th scope="col">Options</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($employees as $employee) {
        ?>
            <tr>
                <th scope="row"><a href="/employee?ssn=<?= $employee->Ssn ?>"><?= $employee->Ssn; ?></a></th>
                <td><?= $employee->Fname . " " . $employee->Lname; ?></td>
                <td><?= $employee->Address; ?></td>
                <td><?= $employee->Salary; ?></td>
                <td><?= "Add" ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>
<form class="container border" method="post" action="/employee">
    <div class="form-group">
        <label for="ssn">Enter Employee Social Security Number:</label>
        <input type="text" class="form-control" name="Ssn">
    </div>
    <div class="form-group">
        <label for="lname">Employee Last name is:</label>
        <input type="text" class="form-control" name="Lname">
    </div>
    <div class="form-group">
        <label for="fname">Employee First name is:</label>
        <input type="text" class="form-control" name="Fname">
    </div>
    <div class="form-group">
        <label for="address">Employee Address is:</label>
        <input type="text" class="form-control" name="Address">
    </div>
    <div class="form-group">
        <label for="salary">Employee Salary is:</label>
        <input type="text" class="form-control" name="Salary">
    </div>
    <div class="form-group">
        <label for="salary">Department Number is:</label>
        <input type="text" class="form-control" name="Dno">
    </div>
    <button type="submit" class="btn btn-primary" name="submit">Submit</button>
</form>