<div class="employee my-3">
    <div class="row gutters-sm">
        <div class="col-md-4 mb-3">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex flex-column align-items-center text-center">
                        <img src="https://bootdey.com/img/Content/avatar/avatar<?= rand(1, 8); ?>.png" alt="Admin" class="rounded-circle" width="150">
                        <div class="mt-3">
                            <h4><?= $employee->getFullname(); ?></h4>
                            <p class="text-secondary mb-1"><?= $employee->Ssn; ?></p>
                            <p class="text-muted font-size-sm"><?= $employee->Address; ?></p>
                            <!-- <button class="btn btn-primary">Follow</button>
                            <button class="btn btn-outline-primary">Message</button> -->
                        </div>
                    </div>
                    <ul class="list-group list-group-flush">
                        <?php foreach ($employee->getDependents() as $dependent) { ?>
                            <li class="list-group-item d-flex justify-content-between align-items-start">
                                <div class="ms-2 me-auto">
                                    <h6 class="fw-bold"><?= $dependent['Dependent_name']; ?></h6>
                                    <span><?= $dependent['Relationship']; ?></span>
                                    -
                                    <span><?= date('F j Y', strtotime($dependent['Bdate'])); ?></span>
                                </div>
                                <span class="badge bg-primary rounded-pill"><?= $dependent['Sex']; ?></span>
                            </li>
                        <?php } ?>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card mb-3">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Full Name</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            <?= $employee->getFullname(); ?>
                        </div>
                    </div>
                    <hr>
                    <?php foreach ($employee->getAttributes() as $value) {
                        if ($value != 'Fname' || $value != 'Lname') {
                    ?>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0"><?= $value; ?></h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <?php if ($value == 'Bdate') {
                                        echo date('F j Y', strtotime($employee->{$value}));
                                    } else {
                                        echo $employee->{$value};
                                    } ?>
                                </div>
                            </div>
                            <hr>
                    <?php }
                    } ?>
                    <div class="row">
                        <div class="col-sm-12">
                            <a class="btn btn-info " target="__blank" href="/">Edit</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row gutters-sm">
                <?php foreach ($employee->getProjects() as $project) { ?>
                    <div class="col-sm-6 mb-3">
                        <div class="card h-100">
                            <div class="card-body">
                                <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2"><?= $project->Pname; ?></i></h6>
                                <?php foreach ($project->getAttributes() as $value) {
                                    if ($value == 'Pname') {
                                        continue;
                                    } ?>
                                    <div class="row">
                                        <div class="col-sm-3">
                                            <h6 class="mb-0"><?= $value; ?></h6>
                                        </div>
                                        <div class="col-sm-9 text-secondary">
                                            <?= $project->{$value}; ?>
                                        </div>
                                    </div>
                                    <hr>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>