<?php

use \general\WebApp;
?>
<div class="row gutters-sm my-3 <?= $cssClasses; ?>">
    <form class="container border col-md-4" method="post" action="<?php echo WebApp::getUrlPath($path); ?>">
        <h3 class="my-3 text-center">Add a <?= $title; ?></h3>
        <?php foreach ($model::getLabels() as $attr => $label) { ?>
            <div class="mb-3">
                <label class="col-form-label fw-bold" for="<?= $attr; ?>"><?= $title . ' ' . $label; ?>:</label>
                <input type="text" id="" class="form-control <?= !$errors[$attr] ?: 'is-invalid'; ?>" name="<?= $attr; ?>" required>
                <div class="invalid-feedback">
                    <?= $errors[$attr][0]; ?>
                </div>
            </div>
        <?php } ?>
        <button type="submit" class="btn btn-primary my-3" name="submit">Add</button>
    </form>
    <div class="col-md-8">
        <table class="table">
            <thead class="thead-primary">
                <tr>
                    <?php foreach ($model::getLabels() as $label) { ?>
                        <th scope="col"><?= $label; ?></th>
                    <?php } ?>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($listItems as $object) { ?>
                    <tr>
                        <?php foreach ($object::getLabels() as $attr => $label) {
                            if ($object->getAttributes()['primarykey'] === $attr) { ?>
                                <th scope="row">
                                    <a href="<?php echo WebApp::getUrlPath("$path?$attr=" . $object->getData($attr)); ?>">
                                        <?= $object->getData($attr); ?>
                                    </a>
                                </th>
                            <?php } else { ?>
                                <td><?= $object->getData($attr); ?></td>
                            <?php } ?>
                        <?php } ?>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>