<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WebProject</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
</head>

<body>
    <header>
        <div class="container-fluid">
            <h1 class="display-4 fw-bold"><a class="text-decoration-none" href="/">The Company</a></h1>
        </div>
        <nav class="navbar navbar-expand-sm navbar-dark bg-primary">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link fw-bold" href="/employees">Employees</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link fw-bold" href="/projects">Projects</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link fw-bold" href="/departments">Departments</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        {{__bodyContent__}}
    </div>
    <footer class="container-fluid bg-secondary text-light text-center">
        <span>Developed by Oliveirs</span>
    </footer>
</body>

</html>