<?php

use \general\WebApp;
?>
<div class="projects row gutters-sm my-3">
    <form class="container border col-md-4" method="post" action="<?php echo WebApp::getUrlPath("/project"); ?>">
        <h3 class="my-3 text-center">Add a Project</h3>
        <div class="mb-3">
            <label class="col-form-label fw-bold" for="Pnumber">Project Number is:</label>
            <input type="text" class="form-control <?= !$errors['Pnumber'] ?: 'is-invalid'; ?>" name="Pnumber" required>
            <div class="invalid-feedback">
                <?= $errors['Pnumber'][0]; ?>
            </div>
        </div>
        <div class="mb-3">
            <label class="col-form-label fw-bold" for="Pname">Project Name is:</label>
            <input type="text" class="form-control <?= !$errors['Pname'] ?: 'is-invalid'; ?>" name="Pname" required>
            <div class="invalid-feedback">
                <?= $errors['Pname'][0]; ?>
            </div>
        </div>
        <div class="my-3">
            <label class="col-form-label fw-bold" for="Plocation">Project Location is:</label>
            <input type="text" class="form-control <?= !$errors['Plocation'] ?: 'is-invalid'; ?>" name="Plocation" required>
            <div class="invalid-feedback">
                <?= $errors['Plocation'][0]; ?>
            </div>
        </div>
        <div class="my-3">
            <label class="col-form-label fw-bold" for="Dnum">Department number is:</label>
            <input type="text" class="form-control <?= !$errors['Dnum'] ?: 'is-invalid'; ?>" name="Dnum" required>
            <div class="invalid-feedback">
                <?= $errors['Dnum'][0]; ?>
            </div>
        </div>
        <button type="submit" class="btn btn-primary my-3" name="submit">Add</button>
    </form>
    <div class="col-md-8">
        <table class="table">
            <thead class="thead-primary">
                <tr>
                    <th scope="col">Project Number</th>
                    <th scope="col">Name</th>
                    <th scope="col">Location</th>
                    <th scope="col">Dnum</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($projects as $project) { ?>
                    <tr>
                        <th scope="row"><a href="<?php echo WebApp::getUrlPath("/project?Pnumber=" . $project->getData('Pnumber')); ?>"><?= $project->getData('Pnumber'); ?></a></th>
                        <td><?= $project->Pname; ?></td>
                        <td><?= $project->Plocation; ?></td>
                        <td><?= $project->Dnum; ?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>