<div class="projects row gutters-sm my-3">
    <form class="container border col-md-4" method="post" action="/project">
        <h3 class="my-3 text-center">Add a Project</h3>
        <div class="mb-3">
            <label class="col-form-label fw-bold" for="Pnumber">Project Number is:</label>

            <input type="text" class="form-control" name="Pnumber">
        </div>
        <div class="mb-3">
            <label class="col-form-label fw-bold" for="Pname">Project name is:</label>
            <input type="text" class="form-control" name="Pname">
        </div>
        <div class="my-3">
            <label class="col-form-label fw-bold" for="Plocation">Project Location is:</label>
            <input type="text" class="form-control" name="Plocation">
        </div>
        <div class="my-3">
            <label class="col-form-label fw-bold" for="Dnum">Department number is:</label>
            <input type="text" class="form-control" name="Dnum">
        </div>
        <button type="submit" class="btn btn-primary my-3" name="submit">Add</button>
    </form>
    <div class="col-md-8">
        <table class="table">
            <thead class="thead-primary">
                <tr>
                    <th scope="col">Project Number</th>
                    <th scope="col">Name</th>
                    <th scope="col">Location</th>
                    <th scope="col">Dnum</th>
                    <th scope="col">Options</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($projects as $project) { ?>
                    <tr>
                        <th scope="row"><a href="/project?Pnumber=<?= $project->Pnumber; ?>"><?= $project->Pnumber; ?></a></th>
                        <td><?= $project->Pname; ?></td>
                        <td><?= $project->Plocation; ?></td>
                        <td><?= $project->Dnum; ?></td>
                        <td><?= "Add" ?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>